### PR TITLE
Use the same shell for :ruby_subprocess_cmd

### PR DESCRIPTION
**Pull request by eregon**
* For instance, I use ZSH and this would shell out to Bash which uses a completely different config.
* `-l` is also harmful in that it resets the PATH instead of inheriting from the parent process.

### CODE REVIEW

**Comment by noahgibbs** [comment]
One difficulty here is that without the "bash -l" wrapper, rvm doesn't reliably work. That's why it's there. I'll look at whether I can move that out into the rvm-savvy runner scripts, though...

**Comment by noahgibbs** [comment]
(Similarly, it's possible to get around this by overriding ruby_subprocess_cmd in the runner)

**Comment by eregon** [comment]
Maybe using `rvm do` would work then? https://rvm.io/workflow/scripting

@mpapis pkuczynski What would you recommend to spawn a command under a selected ruby?

**Comment by eregon** [comment]
@noahgibbs I updated the PR to still wrap in `bash -l -c "COMMAND"` for RVM, but not wrap in other cases.

**Comment by noahgibbs** [comment]
This looks like a great way to handle it. Thanks!

**Comment by eregon** [comment]
Thanks for merging!

**Pull request merged**
